services:
  - type: web
    name: taskforce-system
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: SECRET_KEY
        sync: false
      - key: STAFF_PASSWORD
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: taskforce-db
          property: connectionString

databases:
  - name: taskforce-db
    plan: free


